meta_title: "Comme à la maison - liste de ressources gratuites pour s'occuper"
meta_description: "Partagez vos ressources pour ne pas vous ennuyer pendant cette période de confinement due à l'épidémie de Covid19 (Coronavirus)."
meta_image: "cover.png" # should exist in `app/assets/images/`
